### ISSUE TITLE
Issue in auto-launch and results show in Sonarqube

### ISSUE THREAD

**Issue by CarlosMazo** [lequal/sonar-icode-cnes-plugin#43]
Hi, I'm Carlos Mazo from EUMETSAT, colleague of Jordi Duatis, we talk today via email. Im trying to use the plugin for Sonarqube following the guide but I'm not succeeding. Could you give me some help, or examples please?

Thanks a lot!

### Expected behavior
Being able to see analysis results in SonarQube
Being able to auto-launch Fortran analysis

### Actual behavior
The plugin seems correctly loaded in Sonarqube, as I can see the Quality Profiles in the website.
Can't see analysis results in Sonarqube, when having results extracted manually (by executing the icode analyzer manually) following the plugin user manual
Can't get analysis results from auto-launch analysis, just getting some header of the results like the following:

`<?xml version="1.0" encoding="UTF-8"?>
<analysisProject analysisProjectName="Unknown" analysisProjectVersion="1.0.0">
  <analysisInformations analysisConfigurationId="analysis1" analysisDate="2019-02-11" author="i-Code CNES Analyzer" />
</analysisProject>`

### Steps to reproduce behavior
Follow plugin documentation (probably I misunderstood something)

### Detection version
1.1.0

**Comment by begarco** [comment]
Hi Carlos, can you provide us more information like sonar-scanner output? Feel free to anonymize it if necessary.

**Comment by CarlosMazo** [comment]
Hi, I have tried to get the output in xml and in with res.out extension.

Doing it manually, I am able to extract the code analysis, but in the automatic way, I just get this header:

`<?xml version="1.0" encoding="UTF-8"?> <analysisProject analysisProjectName="Unknown" analysisProjectVersion="1.0.0"> <analysisInformations analysisConfigurationId="analysis1" analysisDate="2019-02-11" author="i-Code CNES Analyzer" /> </analysisProject>`

**Comment by begarco** [comment]
I meant the log of the command `sonar-scanner` not the content of i-Code result file.

- Which client do you use for launching SonarQube analysis?
- Which version of SonarQube doyou use ?

**Comment by CarlosMazo** [comment]
[execution_log.txt](https://github.com/lequal/sonar-icode-cnes-plugin/files/2856670/execution_log.txt)

- I use a custom script for executing the sonar-scanner
- SonarQube 7.3, Sonar-scanner-3.2.0

**Comment by begarco** [comment]
Thanks to your issue, we discovered a bug in the plugin: files are not recursively analyzed by the plugin when the auto launch is used.

Consider using the following work around:
1- run i-Code from command line
2- run sonar-scanner

The plugin will be fixed as soon as possible.

**Comment by CarlosMazo** [comment]
Thank you very much.

About the workaround, I have tried it but Sonarqube still not importing the results.

I run i-Code from command line and generate the report succesfully, but no results shown in the web. I think it should be someting related to the configuration of the project properties file, or the sonar-scanner configuration.

I have tried to configure it like i-Code user guide shows but no hint about the mistake yet. Do you have any recomendation? 

Thanks,
Carlos

**Comment by begarco** [comment]
Ok, can you check following points:
- [ ] path to the i-Code report is correct in SonarQube
- [ ] paths are correct in the i-Code results
- [ ] there are no error or warning in sonar-scanner logs

We are currently working on the fix of the plugin.

**Comment by Leobip** [comment]
Greetings, I think I have a similar problem ... I must have misunderstood the installation or execution instructions, but I can't get the analysis ... it only gives me the headings ... I have installed version 3.1 CLi:
https://github.com/lequal/i-CodeCNES/releases/download/v3.1.0/i-CodeCNES-3.1.0-CLI-win32.win32.x86_64.zip
and I run the Cli version according to the manual and I get nothing in the CLi and of course less in SonarQ ... The plugin in SonarQ is correctly installed because I can see the profiles and the config.

Thanks for your help.

**Comment by begarco** [comment]
https://github.com/lequal/sonar-icode-cnes-plugin/releases/tag/2.0.0-RC1 closes #43

**Comment by alvaroEumetsat** [comment]
Dear all, 
I would like chime in this topic one year later :)

Accordingly to cnes icode quickstart guide https://github.com/cnescatlab/sonar-icode-cnes-plugin, I am using sonarcommunity Version 8.2 with Sonar i-Code CNES plugin 2.0.2 which has been installed from sonarcommunity marketplace,  i-Code has not been installed because it´s optional and we do not need it.

Unfortunately, after launching a couple of scan with sonarcommunity  I have realised that the results are not consistent, I mean launching the same project several times the scan results are different, sometimes shows 120 major issues other times just 80 …
There are several rules which sometimes take them into account and others that they do not, even though is the same project.

Could you please assist me in figuring it out and have consistent results.
Thanks for your help.
